spring:
  application:
    name: x

  datasource:
    url: jdbc:mariadb://localhost:3306/x?useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 300000
      pool-name: SpringBootJPAHikariCP

  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

file:
  upload-dir: "C:/Users/dideh/Desktop/Spring/x/image"

jwt:
  secret: "hasdhfidfhosfjsifjoewifhofhouhsfewhfoiwehfufhowufhoiudhsfoshfoeufhaowehfoudafhsadufhsdafhuisodhfuoshfuewhfuowaehfufhiwhwufwaefwaee"
  expiration: 3600000

server:
  error:
    include-stacktrace: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failure-rate-threshold: 1 # 총 몇 번중에 몇 %
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 2  # 총 몇 번중에
        sliding-window-type: COUNT_BASED
        wait-duration-in-open-state: 10m
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      liveApiCircuitBreaker:
        base-config: default